export const PIN_WINDOW = 'pin-window'
export const SAVE_CONFIG = 'save-config'
export const GET_CONFIG = 'get-config'
export const OPEN_EXTERNAL = 'open-external'
export const CLIPBOARD_CONTENT = 'clipboard-content'
